create table INFORMATION_SCHEMA.ENUM_VALUES
(
    OBJECT_CATALOG  CHARACTER VARYING,
    OBJECT_SCHEMA   CHARACTER VARYING,
    OBJECT_NAME     CHARACTER VARYING,
    OBJECT_TYPE     CHARACTER VARYING,
    ENUM_IDENTIFIER CHARACTER VARYING,
    VALUE_NAME      CHARACTER VARYING,
    VALUE_ORDINAL   CHARACTER VARYING
);

